name: easyorder
description: Manage your orders the simple way !

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.3.2+14

environment:
  sdk: ">=2.17.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5

  another_flushbar: ^1.12.30
#  auth_buttons: ^3.0.0
  awesome_dialog: ^3.1.0
  badges: ^3.1.1
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.8.3
  collection: ^1.17.1
  csv: ^5.0.2
  datetime_picker_formfield: ^2.0.1
  # TODO device_preview: ^0.7.4
  flutter_facebook_auth: ^5.0.10
  flutter_markdown: ^0.6.17
  flutter_slidable: ^3.0.0
  firebase_analytics: ^10.4.4
  firebase_auth: ^4.7.1
  firebase_core: ^2.15.0
  firebase_crashlytics: ^3.3.4
  #  firebase_performance: ^0.7.0+7
  firebase_remote_config: ^4.2.4
  firebase_storage: ^11.2.5
  flutter_hooks: ^0.18.6
  flutter_switch: ^0.3.2
  flutter_typeahead: ^4.6.2
  freezed_annotation: ^2.4.1
  functional_listener: ^2.3.1
  font_awesome_flutter: ^10.5.0
  get_it: ^7.6.0
  google_fonts: ^3.0.1 # https://fonts.google.com/?query=luckiest
  google_sign_in: ^6.1.4
  hooks_riverpod: ^2.3.6
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  http: ^0.13.6
  image_picker: ^1.0.1
  injectable: ^2.1.2
  intl: ^0.18.1
  intl_phone_number_input: ^0.7.3+1
  json_annotation: ^4.8.1
  loading_overlay: ^0.3.0
  logger: ^1.4.0
  mime: ^1.0.4
  package_info: ^2.0.2
  path: ^1.8.3
  path_provider: ^2.0.15
  rxdart: ^0.27.7
  sign_button: ^2.0.4
  scrollable_positioned_list: ^0.3.8
  share: ^2.0.4
  shared_preferences: ^2.2.0
  sticky_headers: ^0.3.0+2
  upgrader: ^8.0.0
  url_launcher: ^6.1.12
  uuid: ^3.0.7

dev_dependencies:
  build_runner:
  custom_lint: ^0.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  injectable_generator: ^2.1.6
  json_serializable: ^6.7.1
  mockito: ^5.4.2
#  mocktail: ^0.3.0
  riverpod_lint: ^1.3.2

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
    - family: LuckiestGuy
      fonts:
        - asset: assets/fonts/LuckiestGuy-Regular.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_icons:
  image_path: "assets/icon/app-icon.png"
  android: "ic_launcher"
  ios: true

flutter_native_splash:

  # This package generates native code to customize Flutter's default white native splash screen
  # with background color and splash image.
  # Customize the parameters below, and run the following command in the terminal:
  # flutter pub run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # flutter pub run flutter_native_splash:remove

  # color or background_image is the only required parameter.  Use color to set the background
  # of your splash screen to a solid color.  Use background_image to set the background of your
  # splash screen to a png image.  This is useful for gradients. The image will be stretch to the
  # size of the app. Only one parameter can be used, color and background_image cannot both be set.
  color: "#c5cae9"
  #background_image: "assets/background.png"

  # Optional parameters are listed below.  To enable a parameter, uncomment the line by removing
  # the leading # character.

  # The image parameter allows you to specify an image used in the splash screen.  It must be a
  # png file and should be sized for 4x pixel density.
  image: assets/splash.png

  # Android 12 handles the splash screen differently than previous versions.  Please visit
  # https://developer.android.com/guide/topics/ui/splash-screen
  # Following are Android 12 specific parameter.
  android_12:
    # The image parameter sets the splash screen icon image.  If this parameter is not specified,
    # the app's launcher icon will be used instead.
    # Please note that the splash screen will be clipped to a circle on the center of the screen.
    # App icon with an icon background: This should be 960×960 pixels, and fit within a circle
    # 640 pixels in diameter.
    # App icon without an icon background: This should be 1152×1152 pixels, and fit within a circle
    # 768 pixels in diameter.
    image: assets/splash.png

    # App icon background color.
    icon_background_color: "#c5cae9"
