// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class ProdFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeKEd-RyJsS-r5ccsxmmz8xrVFxScT1BM',
    appId: '1:895057574265:web:584ae484c976ecab82d7a8',
    messagingSenderId: '895057574265',
    projectId: 'simple-order-manager',
    authDomain: 'simple-order-manager.firebaseapp.com',
    databaseURL: 'https://simple-order-manager.firebaseio.com',
    storageBucket: 'simple-order-manager.appspot.com',
    measurementId: 'G-J051J1W164',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHwZWqPmI7bgGISMixhY4pacCPzpwEjS0',
    appId: '1:895057574265:android:5f57da62ea50cc68',
    messagingSenderId: '895057574265',
    projectId: 'simple-order-manager',
    databaseURL: 'https://simple-order-manager.firebaseio.com',
    storageBucket: 'simple-order-manager.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFQlT4ZwmOdigVRKpS0JJeFsOqYJW19Yg',
    appId: '1:895057574265:ios:5f57da62ea50cc68',
    messagingSenderId: '895057574265',
    projectId: 'simple-order-manager',
    databaseURL: 'https://simple-order-manager.firebaseio.com',
    storageBucket: 'simple-order-manager.appspot.com',
    androidClientId: '895057574265-jveor7725t5hmdv60f8mknhf1mjainvc.apps.googleusercontent.com',
    iosClientId: '895057574265-s4ku91f1phb39f63jbddbn7j05b1r5dd.apps.googleusercontent.com',
    iosBundleId: 'com.manolo.easyorder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFQlT4ZwmOdigVRKpS0JJeFsOqYJW19Yg',
    appId: '1:895057574265:ios:5f57da62ea50cc68',
    messagingSenderId: '895057574265',
    projectId: 'simple-order-manager',
    databaseURL: 'https://simple-order-manager.firebaseio.com',
    storageBucket: 'simple-order-manager.appspot.com',
    androidClientId: '895057574265-jveor7725t5hmdv60f8mknhf1mjainvc.apps.googleusercontent.com',
    iosClientId: '895057574265-s4ku91f1phb39f63jbddbn7j05b1r5dd.apps.googleusercontent.com',
    iosBundleId: 'com.manolo.easyorder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeKEd-RyJsS-r5ccsxmmz8xrVFxScT1BM',
    appId: '1:895057574265:web:f73f0cf6e8088e7782d7a8',
    messagingSenderId: '895057574265',
    projectId: 'simple-order-manager',
    authDomain: 'simple-order-manager.firebaseapp.com',
    databaseURL: 'https://simple-order-manager.firebaseio.com',
    storageBucket: 'simple-order-manager.appspot.com',
    measurementId: 'G-LDKXMQF7S1',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDeKEd-RyJsS-r5ccsxmmz8xrVFxScT1BM',
    appId: '1:895057574265:web:7bd0612b70bd6fa882d7a8',
    messagingSenderId: '895057574265',
    projectId: 'simple-order-manager',
    authDomain: 'simple-order-manager.firebaseapp.com',
    databaseURL: 'https://simple-order-manager.firebaseio.com',
    storageBucket: 'simple-order-manager.appspot.com',
    measurementId: 'G-7QMQ7VHBCR',
  );
}
